### PR TITLE
predefined values in data table

### PR DESCRIPTION
**Pull request by fuenkchen**
In a tool schema we are now able to define predefined values for table arrays, like that:
```
...
"Q:type": "table",
  "Q:options": {
    "predefinedContent": {
      "type": "column",  // can be "column" or "row"
      "index": 0,   // index of column or row
      "predefinedValues": [["category1"], ["category2"]...]  // values as they should appear in the data table
    },
...
```
Based on type and index the row/column will be made read only.
Predefined values will then be written in the data array, if there are no values other than in the column or row at the specified index.

Can be tested together with choropleth tool on test and staging.

One question: It would be also possible to change this config and mechanism so that you could specify more than one readOnly row/column (by passing an array of indexes). But since we do not really know if we'll have further use cases for that, I was not really sure, if that's useful. What do you think?

### CODE REVIEW

**Comment by manuelroth** [comment]
It looks good to me. I have some thoughts on the extensibility of this feature. I think another way to make this more flexible could be define `predefinedValues` for the entire table. I am not sure why it has to be restricted to columns and rows. What do you think about that?

**Comment by fuenkchen** [comment]
With these changes we can now specify a schema like that:

```
...
"Q:type": "table",
  "Q:options": {
    "predefinedContent": {
      "protectOverwrites": true
      "data": [["header1", "header2"], [{"value": "name1", "readOnly": true}]...]  
    },
...
```
- in `data` property one specifies an array of arrays which contain either just plain values which should be written in data table, or an object consisting of the value which should be written and a flag specifying that this cell should be readOnly. 
- I've come to the conclusion that's it's better to set another flag explicitly to define whether overwriting of values is protected
- One should set this flag to true if predefined content is controlled by another property in the schema to avoid states in data tables which are not comprehensible for the user
- if overwrites are protected it will be checked if there are values in data table which are not predefined and blocks overwrites in that case
- if overwrites are not protected one can overwrite each cell - that's of course just possible for all writable cell.

We can also discuss this mechanism once again.

**Comment by manuelroth** [comment]
This looks very good. Do you think in most usecases overwriting predefinedContent is not desirable?- If that is the case I am thinking it would make sense to change the property from `protectOverwrites` to maybe `allowOverwrites`.
So if the default case would be to not allow overwrites. In case overwrites should be allowed one can set this property. What are your thoughts on this?

**Comment by fuenkchen** [comment]
good point, I will change it to `allowOverwrites`

**Pull request merged**
